[project]
name = 'Cosmic-Microstructure-Manipulation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.microscopic-wormhole-creation]
path = 'contracts/microscopic-wormhole-creation.clar'
clarity_version = 2
epoch = 2.5

[contracts.quantum-foam-observation]
path = 'contracts/quantum-foam-observation.clar'
clarity_version = 2
epoch = 2.5

[contracts.spacetime-curvature-experiments]
path = 'contracts/spacetime-curvature-experiments.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
